src/mocks/api/create-store.js
src/mocks/api/seed-data.js
src/mocks/api/server.js
src/react-query-demo/features/entry-creator/entry-creator.js
src/react-query-demo/index.js

Add suppoer for persisting content as base64

Add backend for base64 content

---

src/index.js

Prevent the real API if we're running tests

prevent real API from running in test environment

---

apps/airview-demo/src/App.js
packages/airview-cms/src/features/use-get-all-entries-meta/index.js
packages/airview-cms/src/features/use-get-all-entries-meta/use-get-child-entries-meta.js
packages/airview-cms/src/features/use-get-all-entries-meta/use-get-collection-entries.js
packages/airview-cms/src/features/use-get-all-entries-meta/use-get-entry-meta.js
packages/airview-cms/src/features/use-get-all-entries-meta/use-get-sibling-entries-meta.js
packages/airview-cms/src/index.js

Adds additional selectors for entries meta
closes airwalk-digital/airview-issues#205

205 all entries meta selectors

---

apps/airview-api-demo/package.json
apps/airview-api-demo/src/index.ts
apps/airview-demo/package.json
apps/airview-demo/src/index.js
package-lock.json

Adds ability to selectively use MSW or 'real' api

Add logic to selectively use msw

---

packages/airview-cms-api/src/cms-backend.ts

Remove caching of branches

---

packages/airview-cms/src/features/cms/content-creator/prepare-entry-payload.js
packages/airview-cms/src/features/cms/toolbar/save-changes.js
packages/airview-cms/src/features/cms/use-set-cms-context/use-set-cms-context.js
packages/airview-mock-server/__tests__/airview-mock-server.js
packages/airview-mock-server/src/features/airview-mock-server/create-seed-data.js
packages/airview-mock-server/src/features/airview-mock-server/create-store.js

Closes AirWalk-Digital/airview-issues#224

Replace references of _index.md

---

.github/workflows/publish-packages.yml
apps/airview-demo/package.json
package.json
packages/airview-cms-api/package.json
packages/airview-cms-api/src/github-client.ts
packages/airview-cms/package.json
packages/airview-mock-server/package.json
packages/airview-ui/package.json

Closes AirWalk-Digital/airview-issues#241

Publish to NPM

---

.github/workflows/publish-packages.yml
packages/airview-mock-server/package.json

Add mock server to npm publish

Add mock server to npm publish

---

packages/airview-cms-api/src/cms-backend.ts

closes AirWalk-Digital/airview-issues#250

Cache meta on generation

---

packages/airview-ui/src/stories/documentation-view/documentation-view.doc.md
packages/airview-ui/src/stories/documentation-view/documentation-view.stories.js

Adds `Breadcrumb` component to the `DocumentView` example Story in airview-cms package

Add Breadcrumb to DocumentationView Story example

---

.github/workflows/publish-packages.yml
apps/airview-demo/package.json
packages/airview-compliance-ui/package.json
packages/airview-ui/package.json

Adds ability to push compliance-ui to npm
Closes https://github.com/AirWalk-Digital/airview-issues/issues/266

#266 push compliance UI to npm

---

apps/airview-demo/src/App.js
packages/airview-cms/README.md
packages/airview-cms/src/features/store/airview-api.js

Closes Airwalk-Digital/airview-issues#265

Make base url dynamic

---

deployment/airview-cms-api-aws-lambda-wrapper/package.json
deployment/airview-cms-api-aws-lambda-wrapper/src/Api/Cms/Content/DeleteContentEntity.ts
deployment/airview-cms-api-aws-lambda-wrapper/src/Api/Cms/Content/PutContentEntity.ts
deployment/airview-cms-api-aws-lambda-wrapper/src/Handler/CmsApiHandler.ts

Add call to pull author from cookie to support correct authoring as per Airwalk-digital/airview-issues#249

Add call to pull author from cookie

---

deployment/airview-cms-api-aws-lambda-wrapper/src/Handler/CmsApiHandler.ts

closes airwalk-digital/airview-issues#268

get github client from singleton factory

---

packages/airview-compliance-ui/src/features/application-tile/application-tile-call-to-action-button.js

Fixes invalid props on ApplicationTileCallToActionButton and removes prop-type errors

FIx invalid props on ApplicationTileCallToActionButton

---

apps/airview-demo/src/layouts/main-layout/main-layout.js
apps/airview-demo/src/layouts/main-layout/search.js
packages/airview-ui/src/features/search/search.js
packages/airview-ui/src/stories/documentation-view/documentation-view.doc.md
packages/airview-ui/src/stories/documentation-view/documentation-view.stories.js

- Fixes layout issue with Search Component `airview-ui`
- Adds search UI to documentation view story `airview-ui`
- Adds search UI to `airview-demo`

271 add search UI to demo

---

packages/airview-cms/README.md

Adds example to airview-cms documentation for collections and entries
closes airwalk-digital/airview-issues#261

#261 add example to airview-cms collections and entries docs

---

packages/airview-compliance-ui/src/features/compliance-table/compliance-table.common-styles.js

Fixes horizontal overflow on ComplianceTable component exported from airview-compliance-ui package
closes airwalk-digital/airview-issues#275

#275: Fix overflow on ComplianceTable component

---

packages/airview-compliance-ui/src/features/compliance-table/compliance-table-row-detail.styles.js
packages/airview-compliance-ui/src/stories/compliance-table/applications-data.js

Fixes horizontal scroll on ComplianceTable when passing multiple resource instances data.
closes airwalk-digital/airview-issues#275

#275: Fix overflow in complianceTable with multi instances

---

apps/airview-demo/src/App.js
apps/airview-demo/src/config.js
packages/airview-cms/src/features/index.js
packages/airview-cms/src/features/use-get-branches/index.js
packages/airview-cms/src/features/use-get-branches/use-get-current-branch.js
packages/airview-cms/src/index.js

Closes airwalk-digital/airview-issues#280

Add branch hooks to cms, fix demo app to not require env var

---

packages/airview-cms/src/features/cms/body-editor/body-editor.slice.js
packages/airview-cms/src/features/cms/content-creator/prepare-entry-payload.js
packages/airview-cms/src/features/cms/meta-editor/meta-editor.slice.js
packages/airview-cms/src/features/cms/toolbar/save-changes.js

closes airwalk-digital/airview-issues#283

Use utf8 when converting content

---

packages/airview-cms/src/features/cms/body-editor/markdown-resolver.js

closes airwalk-digital/airview-issues#299

Skip Unresolvable Images

---

packages/airview-cms/src/features/cms/body-editor/markdown-editor.js
packages/airview-cms/src/features/cms/config-slice/config.slice.js
packages/airview-cms/src/features/cms/config-slice/index.js

closes airwalk-digital/airview-issues#313

Fix images not resolving

---

.gitignore
package-lock.json
packages/airview-compliance-ui/.storybook/main.js
packages/airview-compliance-ui/package.json
packages/airview-ui/.storybook/main.js
packages/airview-ui/package.json

Adds required fixes to prevent Storybook build errors for dev and production within `airview-ui` and `airview-compliance-ui` packages.
closes airwalk-digital/airview-issues#318

#318: Fix failing Storybook builds (dev and prod)

---

apps/airview-demo/src/App.js
apps/airview-demo/src/views/home-page-view.js
apps/airview-demo/src/views/index.js

Closes airwalk-digital/airview-issues#327

Fix routing of demo app to static homepage

---

packages/airview-cms/README.md
packages/airview-cms/src/features/cms/index.js
packages/airview-cms/src/features/cms/use-enable-branch-via-search-param/index.js
packages/airview-cms/src/features/cms/use-enable-branch-via-search-param/use-enable-branch-via-search-param.js
packages/airview-cms/src/views/main-view/main-view.js

closes airwalk-digital/airview-issues#303

#303 enable preview mode in any branch

---

deployment/airview-cms-api-aws-lambda-wrapper/src/api/getExternalContentByRepoOwner.ts
deployment/airview-cms-api-aws-lambda-wrapper/src/api/index.ts

Add missing external content endpoint AWS Wrapper

feat: add external content lambda wrapper

---

apps/airview-api-demo/src/index.ts
apps/airview-demo/src/App.js
apps/airview-demo/src/config.js
apps/airview-demo/src/views/document-view/document-view.js
packages/airview-cms/src/features/cms/body-editor/markdown-editor.js
packages/airview-html-to-pdf-util/src/use-html-to-pdf-util.ts
packages/airview-mock-server/src/features/airview-mock-server/airview-mock-server.js
packages/airview-mock-server/src/features/airview-mock-server/create-seed-data.js
packages/airview-mock-server/src/features/airview-mock-server/markdown-content.md

**Fixes:**
- Corrects endpoint for print request in `airview-html-to-pdf-util` package airwalk-digital/airview-issues#344
**Changes**
- Disables MDX support until solution is found to support images
- Changes endpoint of `airview-api-demo`

Various bug fixes and changes

---

apps/airview-api-demo/src/index.ts
apps/airview-demo/src/views/document-view/external-content.js

Fix the problem: image is not correct loaded in the external content.

Fix external content image

---

deployment/airview-cms-api-aws-lambda-wrapper/package-lock.json
deployment/airview-cms-api-aws-lambda-wrapper/package.json
deployment/airview-cms-api-aws-lambda-wrapper/src/api/getExternalMediaByRepoOwner.ts
deployment/airview-cms-api-aws-lambda-wrapper/src/api/index.ts

Adds reusable code for getting external media

Add exteral media function for lambda usage

---

apps/airview-demo/src/layouts/main-layout/use-get-navigation-items-data.js
package-lock.json
packages/airview-cms-api/src/cms-backend.ts
packages/airview-cms-api/src/interfaces.ts
packages/airview-cms/package.json
packages/airview-cms/rollup.config.js
packages/airview-cms/src/features/cms/body-editor/markdown-editor.js
packages/airview-cms/src/features/cms/body-editor/mdx-content.js

Closes airwalk-digital/airview-issues#354

Conditonally render mdx and handle failure gracefully

---

packages/airview-cms/src/features/cms/body-editor/markdown-editor.js

Fixes typo in renderer to allow for correct fallback component

Fix renderer typo

---

apps/airview-api-demo/package.json
apps/airview-api-demo/src/index.ts
package-lock.json

Adds dynamic recogintion of file types to media

Add mime types to demo

---

packages/airview-cms-api/src/cms-backend.ts
packages/airview-cms/src/features/cms/body-editor/markdown-editor.js

Fixes issue with relative images
Skips over unparsable frontmatter

Fix relative link image rendering
